name: Hola Mundo

on:
  push:
    branches:
      - aprendiendo-github-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
      - run: node main.js