name: Triggers
run-name: ¡Estoy aprendiendo a usar diferentes Triggers!
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.js'
  issues:
    types:
      - labeled
  workflow_dispatch:
    inputs:
      lenguaje_favorito:
        description: 'Lenguaje favorito'
        default: Javascript
        required: true
        type: choice
        options:
        - Python
        - JavaScript
        - Go
      nombre:
        description: 'Tu nombre'
        required: true
        default: Juan
        type: string
  schedule:
    - cron:  '15 22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v1
      - run: node main.js
